# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
   
#     # Runs a single command using the runners shell
#     - name: Run a one-line script
#       run: echo Hello, world!

#     # Runs a set of commands using the runners shell
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        
    - uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  
        
#     - name: Install GatsbyJS CLI
#       run: npm install -g gatsby-cli
    
    - name: Install gh-pages
      run: npm install -g gh-pages
        
#     - name: Install Dependencies
#       run: npm install
      
#     - name: Add .env
#       run: echo 'DATO_API_TOKEN=${{ secrets.DATO_API_TOKEN }}' >> .env
      
#     - name: Build
#       run: gatsby build --prefix-paths 
      
    - name: Deploy
#       env:
#         GH_PAGES = ${{ secrets.GH_PAGES }}
#       run: npm run deploy
      run: |
        echo ${{ secrets.GH_PAGES }}
        gh-pages -d public -r https://${{ secrets.GH_PAGES }}@github.com/ronald-chun/gatsby-cloud.git

